### ISSUE TITLE
Imgur settings

### ISSUE THREAD

**Issue by northeaster** [johnlewissims/upload-video#1]
![image](https://user-images.githubusercontent.com/55854510/83327523-357dac00-a285-11ea-8b97-adaf857f0a60.png)
Can you explain imgur settings in detail?

**Comment by johnlewissims** [comment]
Gladly! 

I have this in the readme currently. 

"Navigate to 'Settings' and enter your Client ID from Imgur, Imgur Endpoint (https://api.imgur.com/3/upload) and Max File Size in MB."

The client ID is the token imgur uses to identify where the uploads are coming from.  So just go to their website and register here (https://api.imgur.com/oauth2/addclient).  

The Imgur Endpoint is the route you need to call for uploading images. For most that route is https://api.imgur.com/3/upload.

**Comment by northeaster** [comment]
![image](https://user-images.githubusercontent.com/55854510/83334165-40e4cd80-a2ad-11ea-9353-950e41ea73aa.png)
which?

**Comment by johnlewissims** [comment]
#2
