### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by LCinHK** [johnlewissims/upload-video#2]
```
HTTP/2 400 Bad Request
date: Sat, 04 Jul 2020 13:51:26 GMT
content-type: application/json; charset=utf-8
x-ratelimit-clientlimit: 12500
x-ratelimit-clientremaining: 12498
x-ratelimit-clientreset: 86234
x-ratelimit-userlimit: 500
x-ratelimit-userremaining: 499
x-ratelimit-userreset: 3600
cf-cache-status: DYNAMIC
cf-request-id: 03bbb1a936000004ffafa82200000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 5ad95221f92104ff-LAX
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
X-Firefox-Spdy: h2
```
How?

**Comment by johnlewissims** [comment]
Please clarify the difficulty you are having.  Where does this error occur? During installation? After activation?

**Comment by LCinHK** [comment]
> 
> 
> After activation  

This issue happened during the upload process with endpoint `https://api.imgur.com/3/upload`. I used the exact same client ID of  the one used in https://github.com/matteocontrini/flarum-imgur-upload

**Comment by johnlewissims** [comment]
Follow up question.  Is this error returned for the POST request or the GET request?

**Comment by LCinHK** [comment]
> Follow up question. Is this error returned for the POST request or the GET request?


On the POST request

**Comment by johnlewissims** [comment]
I'm having a hard time replicating this issue. There is a known issue with the GET request by the client after upload. I was hoping that this would be the same issue. 

Give me your environment details.  Run flarum info and put the output in here and we'll try and debug from there.

**Comment by LCinHK** [comment]
It seems to be a problem related to file size or timeout. I just succeeded uploading a 874kb video. Larger videos(bigger than 10mb) always get a 400 error

**Comment by LCinHK** [comment]
@johnlewissims  Can you add a feature of replacing `https://i.imgur.com`? Both the endpoint `https://api.imgur.com` and that is not available in some countries where we need to replace it into a proxy URL

**Comment by johnlewissims** [comment]
Thanks for the update. That's odd.  Imgur allowed 200MB or less last time I checked.  Maybe there was an update on their end? I'll check.

You can adjust the endpoint in Settings already.  The difficulty is that if you call from another provider (ex. Amazon S3), the extension won't be able to handle the response. I hope to add support for Amazon S3 in the next month.  Was there another provider you were hoping to add?

**Comment by LCinHK** [comment]
Sorry if I made you misunderstood something.
What I meant was: "Imgur is unavailable in my and some countries, so that I have set up a proxy on my server(e.g: using something like `https://proxy.mydomaserver.com/Imgur/imageid` to access an image on `https://i.imgur.com/imageid`). The endpoint settings already solved the upload issue where I can change `https://api.imgur.com` into my proxy, but it will be better if I can changed the `Https://i.imgur.com` part in to proxy part so that my users will be able to use it."

I have modified an imgur image upload extension to reach that function, but I found difficulties trying to modify this one: cannot find js/src

**Comment by johnlewissims** [comment]
Ahh! Now I see the difficulty. This will be more difficult to achieve as
the endpoint comes directly from Imgur.

Can you load the videos from your proxy server? What does that url look
like?

**Comment by LCinHK** [comment]
>  Can you load the videos from your proxy server? What does that url look like?

Yes. I have written a guide (in Chinese) and I believe everyone who uses nginx as their web server can easily do it.
```
location ^~ /imgur/ {
			proxy_pass https://i.imgur.com/;
			proxy_buffering off;
			proxy_set_header Referer "";
			proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36";
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Upgrade "websocket";
			proxy_set_header Connection "Upgrade";
		}
```
With this, you can simply replace `https://i.imgur.com` into `https://yourforum.com/imgur` in image URL to achieve same thing.

> That's odd. Imgur allowed 200MB or less last time I checked. Maybe there was an update on their end? I'll check.

Just found out that the problem was my super slow connection. Uploading 10MB took 2 minutes and that should be the error
